from django import forms
from models import MaterialEnfermeria

class MaterialForm(forms.ModelForm):

	class Meta:
		model = MaterialEnfermeria 

		fields = (
			'expediente',
			'abatelenguas',
			'acrilico',
			'aguja_corta',
			'aguja_larga',
			'agua_oxi',
			'alcohol',
			'alginato',
			'algodon',
			'alvogil',
			'amalgama',
			'amagloss',
			'lidocaina',
			'scandonest_2',
			'scandonest_3',
			'ctz',
			'banda_acero',
			'benzal',
			'bond',
			'cavit',
			'cemento',
			'cinta_testigo',
			'corona_acero',
			'cresophene',
			'dique_hule',
			'dycal',
			'formocresol',
			'fluoruro',
			'gasas',
			'hidro_calcio',
			'hilo_dique',
			'hilo_retractor',
			'hipoclorito',
			'h_bisturi_sutura',
			'h_cera_roja',
			'h_cera_rosa',
			'irm',
			'ionomero_reconstruccion',
			'ionomero_cementacion',
			'modelina',
			'monomero',
			'papel_articular',
			'pastilla_reveladora',
			'pasta_profilactica',
			'permalastic',
			'placa_b_sup_inf',
			'puntas_accesorias',
			'puntas_principales',
			'puntas_papel',
			'resina_ac_grabador',
			'resina_fluida',
			'sellador',
			'sealapex',
			'lija_celuloide',
			'yeso_piedra',
			'yeso_velmix',
			'zoe',
			'z_plus_act_b',
			)