# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from Usuarios.models import Usuario

class MaterialEnfermeria(models.Model):
	fecha = models.DateTimeField(u'Fecha', auto_now_add=True)
	usuario_material = models.ForeignKey(Usuario, related_name='user_material')
	expediente = models.CharField(u'Expediente', max_length= 15)
	abatelenguas = models.IntegerField(u'Abatelenguas', default=0)
	acrilico = models.IntegerField(u'Acrilico', default=0)
	aguja_corta = models.IntegerField(u'Aguja Corta', default=0)
	aguja_larga = models.IntegerField(u'Aguja Larga', default=0)
	agua_oxi = models.IntegerField(u'Agua Oxigenada', default=0)
	alcohol = models.IntegerField(u'Alcohol', default=0)
	alginato = models.IntegerField(u'Alginato', default=0)
	algodon = models.IntegerField(u'Algodon', default=0)
	alvogil = models.IntegerField(u'Alvolgil', default=0)
	amalgama = models.IntegerField(u'Amalgama', default=0)
	amagloss = models.IntegerField(u'Amagloss', default=0)
	lidocaina = models.IntegerField(u'Anestesico Lidocaina', default=0)
	scandonest_2 = models.IntegerField(u'Scandonest 2%', default=0)
	scandonest_3 = models.IntegerField(u'Scandonest 3%', default=0)
	ctz = models.IntegerField(u'CTZ', default=0)
	banda_acero = models.IntegerField(u'Banda de Acero', default=0)
	benzal = models.IntegerField(u'Benzal', default=0)
	bond = models.IntegerField(u'BOND', default=0)
	cavit = models.IntegerField(u'CAVIT', default=0)
	cemento = models.IntegerField(u'Cemento Profesional', default=0)
	cinta_testigo = models.IntegerField(u'Cinta Testigo', default=0)
	corona_acero= models.IntegerField(u'Corona de Acero', default=0)
	cresophene = models.IntegerField(u'Cresophene', default=0)
	dique_hule = models.IntegerField(u'Dique de Hule', default=0)
	dycal= models.IntegerField(u'DYCAL', default=0)
	formocresol = models.IntegerField(u'Formocresol', default=0)
	fluoruro = models.IntegerField(u'Fluoruro', default=0)
	gasas = models.IntegerField(u'Gasas', default=0)
	hidro_calcio = models.IntegerField(u'Hidroxido de Calcio', default=0)
	hilo_dique = models.IntegerField(u'Hilo Dique/Dental', default=0)
	hilo_retractor = models.IntegerField(u'Hilo Retractor', default=0)
	hipoclorito = models.IntegerField(u'Hipoclorito', default=0)
	h_bisturi_sutura = models.IntegerField(u'Hoja Bisturi/Sutura', default=0)
	h_cera_roja = models.IntegerField(u'Hoja de Cera Roja', default=0)
	h_cera_rosa = models.IntegerField(u'Hoja de Cera Rosa', default=0)
	irm = models.IntegerField(u'IRM', default=0)
	ionomero_reconstruccion = models.IntegerField(u'Ionomero de Vidrio Reconstruccion', default=0)
	ionomero_cementacion = models.IntegerField(u'Ionomero de Vidrio Cementacion', default=0)
	modelina = models.IntegerField(u'Modelina', default=0)
	monomero = models.IntegerField(u'Monomero', default=0)
	papel_articular = models.IntegerField(u'Papel Articular', default=0)
	pastilla_reveladora = models.IntegerField(u'Pastilla Reveladora', default=0)
	pasta_profilactica = models.IntegerField(u'Pasta Profilactica', default=0)
	permalastic = models.IntegerField(u'Permalastic', default=0)
	placa_b_sup_inf = models.IntegerField(u'Placa Base Sup/Inf', default=0)
	puntas_accesorias = models.IntegerField(u'Puntas Accesorias', default=0)
	puntas_principales = models.IntegerField(u'Puntas Principales', default=0)
	puntas_papel = models.IntegerField(u'Puntas de Papel', default=0)
	resina_ac_grabador = models.IntegerField(u'Resina/Acido Grabador', default=0)
	resina_fluida = models.IntegerField(u'Resina Fluida', default=0)
	sellador = models.IntegerField(u'Sellador', default=0)
	sealapex = models.IntegerField(u'Sealapex', default=0)
	lija_celuloide = models.IntegerField(u'Tira de Lija/Celuloide', default=0)
	yeso_piedra = models.IntegerField(u'Yeso de Piedra', default=0)
	yeso_velmix = models.IntegerField(u'Yeso Velmix', default=0)
	zoe = models.IntegerField(u'ZOE', default=0)
	z_plus_act_b = models.IntegerField(u'Z-Plus/ACT/Base', default=0)
	



