# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 22:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinicaintegral',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_integral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinicacontrolado',
            name='Estado_Civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Civil'),
        ),
        migrations.AddField(
            model_name='historiaclinicacontrolado',
            name='Sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Sexo'),
        ),
        migrations.AddField(
            model_name='historiaclinicacontrolado',
            name='cabeza_perfil',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Perfil'),
        ),
        migrations.AddField(
            model_name='historiaclinicacontrolado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Estado'),
        ),
        migrations.AddField(
            model_name='historiaclinicacontrolado',
            name='tipo_craneo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.TipoCraneo'),
        ),
        migrations.AddField(
            model_name='historiaclinicacontrolado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_controlado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Estado_Civil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Civil'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='Sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Sexo'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.Estado'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_urgencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
