# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0002_auto_20180818_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='Motivo_Consulta',
            field=models.TextField(verbose_name='Motivo de Consulta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='Signos_Sintomas',
            field=models.TextField(verbose_name='Signos y Sintomas que refiere el Paciente'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descrip_act',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion de Actividad'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descrip_notas',
            field=models.TextField(default='', verbose_name='Descripci\xf3n de Notas de Actividades'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(default='', verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hallazgo_dientes',
            field=models.TextField(default='', verbose_name='Dientes'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hallazgo_piel_an',
            field=models.TextField(default='', verbose_name='Piel y Anexos'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='hallazgo_tejidos',
            field=models.TextField(default='', verbose_name='Tejidos Blandos'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='interpretacion_radio',
            field=models.TextField(blank=True, null=True, verbose_name='Interpretacion Radiografica'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medi_cual',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='medi_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='pronostico',
            field=models.TextField(default='', verbose_name='Pronostico'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tipo_alergia',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual tipo de alergia?'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tipo_atencion',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfDe que tipo?'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tratamiento_seguimiento',
            field=models.TextField(default='', verbose_name='Tratamiento que se propone y secuencia del mismo'),
        ),
    ]
