# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0004_auto_20180830_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='Ante_Pato',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes no Patologicos'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descrip_act',
            field=models.TextField(blank=True, verbose_name='Descripcion de Actividad'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='otras_enfermedades',
            field=models.TextField(blank=True, null=True, verbose_name='Otras:'),
        ),
    ]
