# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0005_auto_20180830_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='descrip_act',
            field=models.TextField(default='', verbose_name='Descripcion de Actividad'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='descrip_notas',
            field=models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n de Notas de Actividades'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='abortos',
            field=models.IntegerField(default=0, verbose_name='Abortos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='anestesia_especificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Especifique'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='antecedentes',
            field=models.TextField(default='', verbose_name='Antecedentes Heredo Familiares'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='cara',
            field=models.TextField(default='', verbose_name='Cara'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='cesareas',
            field=models.IntegerField(default=0, verbose_name='Cesareas'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='complicaciones',
            field=models.TextField(default=0, verbose_name='Complicaciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='cuales_alimentos',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='cuales_medicamentos',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='dh_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='dm_tipo',
            field=models.TextField(default='', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_cardio',
            field=models.TextField(default='', verbose_name='Cardiovascular'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_digestivo',
            field=models.TextField(default='', verbose_name='Digestivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_endo',
            field=models.TextField(default='', verbose_name='Endocrino'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_geni',
            field=models.TextField(default='', verbose_name='Genitourinario'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_mus_esque',
            field=models.TextField(default='', verbose_name='Musculo-Esqueletico'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_nervioso',
            field=models.TextField(default='', verbose_name='Nervioso'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_respiratorio',
            field=models.TextField(default='', verbose_name='Respiratorio'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='inter_tegu',
            field=models.TextField(default='', verbose_name='Tegumentario'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='labios',
            field=models.TextField(default='', verbose_name='Labios'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='medi_cuales',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='medi_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='motivo_hospi',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='motivo_medicos',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='np_domiciliarios',
            field=models.TextField(default='', verbose_name='Servicios Domiciliarios'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='np_higiene_personal',
            field=models.TextField(blank=True, null=True, verbose_name='Higiene Personal'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='np_higiene_vivienda',
            field=models.TextField(blank=True, null=True, verbose_name='Higiene de Vivienda'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='num_embarazos',
            field=models.IntegerField(default=0, verbose_name='No. de Embarazos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='num_partos',
            field=models.IntegerField(default=0, verbose_name='No. de Partos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='otras_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Otras Observaciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='padecimiento',
            field=models.TextField(default='', verbose_name='Padecimiento Actual'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='pp_cardiacos',
            field=models.TextField(default='', verbose_name='Cardiacos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='pp_hepaticos',
            field=models.TextField(default='', verbose_name='Hepaticos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='pp_nutricionales',
            field=models.TextField(default='', verbose_name='Nutricionales'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='pp_trans_sexual',
            field=models.TextField(default='', verbose_name='Enfermedades de Transmision Sexual(SIDA)'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='reaccion_especificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Especifique'),
        ),
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='tras_sangre_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iabortos',
            field=models.IntegerField(default=0, verbose_name='Abortos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ianestesia_especificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Especifique'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iantecedentes',
            field=models.TextField(default='', verbose_name='Antecedentes Heredo Familiares'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='icara',
            field=models.TextField(default='', verbose_name='Cara'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='icesareas',
            field=models.IntegerField(default=0, verbose_name='Cesareas'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='icomplicaciones',
            field=models.TextField(default=0, verbose_name='Complicaciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='icuales_alimentos',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='icuales_medicamentos',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='idh_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='idm_tipo',
            field=models.TextField(blank=True, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_cardio',
            field=models.TextField(default='', verbose_name='Cardiovascular'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_digestivo',
            field=models.TextField(default='', verbose_name='Digestivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_endo',
            field=models.TextField(default='', verbose_name='Endocrino'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_geni',
            field=models.TextField(default='', verbose_name='Genitourinario'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_mus_esque',
            field=models.TextField(default='', verbose_name='Musculo-Esqueletico'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_nervioso',
            field=models.TextField(default='', verbose_name='Nervioso'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_respiratorio',
            field=models.TextField(default='', verbose_name='Respiratorio'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iinter_tegu',
            field=models.TextField(default='', verbose_name='Tegumentario'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ilabios',
            field=models.TextField(default='', verbose_name='Labios'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='imedi_cuales',
            field=models.TextField(blank=True, null=True, verbose_name='\xbfCual(es)?'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='imedi_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='imotivo_hospi',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='imotivo_medicos',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='inp_alimentacion',
            field=models.TextField(default='', verbose_name='Alimentacion'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='inp_domiciliarios',
            field=models.TextField(default='', verbose_name='Servicios Domiciliarios'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='inp_higiene_bucal',
            field=models.TextField(default='', verbose_name='Higiene Bucal'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='inum_embarazos',
            field=models.IntegerField(default=0, verbose_name='No. de Embarazos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='inum_partos',
            field=models.IntegerField(default=0, verbose_name='No. de Partos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='iotras_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Otras Observaciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ipadecimiento',
            field=models.TextField(default='', verbose_name='Padecimiento Actual'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ipp_cardiacos',
            field=models.TextField(default='', verbose_name='Cardiacos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ipp_hepaticos',
            field=models.TextField(default='', verbose_name='Hepaticos'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ipp_nutricionales',
            field=models.TextField(default='', verbose_name='Nutricionales'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ipp_trans_sexual',
            field=models.TextField(default='', verbose_name='Enfermedades de Transmision Sexual(SIDA)'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='ireaccion_especificacion',
            field=models.TextField(blank=True, null=True, verbose_name='Especifique'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='itras_sangre_motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
    ]
