# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0007_auto_20180831_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='dm_tipo',
            field=models.TextField(blank=True, default='', verbose_name='Tipo'),
        ),
    ]
