# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoriaClinica', '0009_auto_20180901_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinicacontrolado',
            name='trans_sangre_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la transfuci\xf3n'),
        ),
        migrations.AlterField(
            model_name='historiaclinicaintegral',
            name='itrans_sangre_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la transfuci\xf3n'),
        ),
    ]
