# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_estudiante',
            field=models.BooleanField(default=False),
        ),
    ]
