# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_usuario_is_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_docente',
            field=models.BooleanField(default=False, verbose_name='Soy Docente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_estudiante',
            field=models.BooleanField(default=False, verbose_name='Soy estudiante'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_medico',
            field=models.BooleanField(default=False, verbose_name='Soy M\xe9dico Externo'),
        ),
    ]
