# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocenteAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField(default=0, verbose_name='D\xedas de Trabajo')),
                ('asistencia', models.IntegerField(default=0, verbose_name='Asistencia')),
                ('calificacion', models.IntegerField(default=0, verbose_name='Calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_docente', models.ImageField(default='us_alumno.png', upload_to='imagen-docente', verbose_name='Foto de Perfil')),
                ('alumnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.PerfilAlumno')),
            ],
        ),
    ]
