# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0003_auto_20180806_1841'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfildocente',
            name='perfil_docente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docentealumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.PerfilAlumno'),
        ),
    ]
