# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-17 05:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0002_auto_20180816_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildocente',
            name='perfil_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_docente', to=settings.AUTH_USER_MODEL),
        ),
    ]
