# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-17 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docente', '0003_auto_20180817_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfildocente',
            name='alumnos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.PerfilAlumno'),
        ),
    ]
