# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEnfermeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('expediente', models.CharField(max_length=15, verbose_name='Expediente')),
                ('abatelenguas', models.IntegerField(default=0, verbose_name='Abatelenguas')),
                ('acrilico', models.IntegerField(default=0, verbose_name='Acrilico')),
                ('aguja_corta', models.IntegerField(default=0, verbose_name='Aguja Corta')),
                ('aguja_larga', models.IntegerField(default=0, verbose_name='Aguja Larga')),
                ('agua_oxi', models.IntegerField(default=0, verbose_name='Agua Oxigenada')),
                ('alcohol', models.IntegerField(default=0, verbose_name='Alcohol')),
                ('alginato', models.IntegerField(default=0, verbose_name='Alginato')),
                ('algodon', models.IntegerField(default=0, verbose_name='Algodon')),
                ('alvogil', models.IntegerField(default=0, verbose_name='Alvolgil')),
                ('amalgama', models.IntegerField(default=0, verbose_name='Amalgama')),
                ('amagloss', models.IntegerField(default=0, verbose_name='Amagloss')),
                ('lidocaina', models.IntegerField(default=0, verbose_name='Anestesico Lidocaina')),
                ('scandonest_2', models.IntegerField(default=0, verbose_name='Scandonest 2%')),
                ('scandonest_3', models.IntegerField(default=0, verbose_name='Scandonest 3%')),
                ('ctz', models.IntegerField(default=0, verbose_name='CTZ')),
                ('banda_acero', models.IntegerField(default=0, verbose_name='Banda de Acero')),
                ('benzal', models.IntegerField(default=0, verbose_name='Benzal')),
                ('bond', models.IntegerField(default=0, verbose_name='BOND')),
                ('cavit', models.IntegerField(default=0, verbose_name='CAVIT')),
                ('cemento', models.IntegerField(default=0, verbose_name='Cemento Profesional')),
                ('cinta_testigo', models.IntegerField(default=0, verbose_name='Cinta Testigo')),
                ('corona_acero', models.IntegerField(default=0, verbose_name='Corona de Acero')),
                ('cresophene', models.IntegerField(default=0, verbose_name='Cresophene')),
                ('dique_hule', models.IntegerField(default=0, verbose_name='Dique de Hule')),
                ('dycal', models.IntegerField(default=0, verbose_name='DYCAL')),
                ('formocresol', models.IntegerField(default=0, verbose_name='Formocresol')),
                ('fluoruro', models.IntegerField(default=0, verbose_name='Fluoruro')),
                ('gasas', models.IntegerField(default=0, verbose_name='Gasas')),
                ('hidro_calcio', models.IntegerField(default=0, verbose_name='Hidroxido de Calcio')),
                ('hilo_dique', models.IntegerField(default=0, verbose_name='Hilo Dique/Dental')),
                ('hilo_retractor', models.IntegerField(default=0, verbose_name='Hilo Retractor')),
                ('hipoclorito', models.IntegerField(default=0, verbose_name='Hipoclorito')),
                ('h_bisturi_sutura', models.IntegerField(default=0, verbose_name='Hoja Bisturi/Sutura')),
                ('h_cera_roja', models.IntegerField(default=0, verbose_name='Hoja de Cera Roja')),
                ('h_cera_rosa', models.IntegerField(default=0, verbose_name='Hoja de Cera Rosa')),
                ('irm', models.IntegerField(default=0, verbose_name='IRM')),
                ('ionomero_reconstruccion', models.IntegerField(default=0, verbose_name='Ionomero de Vidrio Reconstruccion')),
                ('ionomero_cementacion', models.IntegerField(default=0, verbose_name='Ionomero de Vidrio Cementacion')),
                ('modelina', models.IntegerField(default=0, verbose_name='Modelina')),
                ('monomero', models.IntegerField(default=0, verbose_name='Monomero')),
                ('papel_articular', models.IntegerField(default=0, verbose_name='Papel Articular')),
                ('pastilla_reveladora', models.IntegerField(default=0, verbose_name='Pastilla Reveladora')),
                ('pasta_profilactica', models.IntegerField(default=0, verbose_name='Pasta Profilactica')),
                ('permalastic', models.IntegerField(default=0, verbose_name='Permalastic')),
                ('placa_b_sup_inf', models.IntegerField(default=0, verbose_name='Placa Base Sup/Inf')),
                ('puntas_accesorias', models.IntegerField(default=0, verbose_name='Puntas Accesorias')),
                ('puntas_principales', models.IntegerField(default=0, verbose_name='Puntas Principales')),
                ('puntas_papel', models.IntegerField(default=0, verbose_name='Puntas de Papel')),
                ('resina_ac_grabador', models.IntegerField(default=0, verbose_name='Resina/Acido Grabador')),
                ('resina_fluida', models.IntegerField(default=0, verbose_name='Resina Fluida')),
                ('sellador', models.IntegerField(default=0, verbose_name='Sellador')),
                ('sealapex', models.IntegerField(default=0, verbose_name='Sealapex')),
                ('lija_celuloide', models.IntegerField(default=0, verbose_name='Tira de Lija/Celuloide')),
                ('yeso_piedra', models.IntegerField(default=0, verbose_name='Yeso de Piedra')),
                ('yeso_velmix', models.IntegerField(default=0, verbose_name='Yeso Velmix')),
                ('zoe', models.IntegerField(default=0, verbose_name='ZOE')),
                ('z_plus_act_b', models.IntegerField(default=0, verbose_name='Z-Plus/ACT/Base')),
            ],
        ),
    ]
