# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialenfermeria',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
