# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialenfermeria',
            name='usuario_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_material', to=settings.AUTH_USER_MODEL),
        ),
    ]
