# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0001_initial'),
        ('HistoriaClinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilalumno',
            name='pacientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.HistoriaClinica'),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='pacientes_controlados',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.HistoriaClinicaControlado'),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='pacientes_integal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HistoriaClinica.HistoriaClinicaIntegral'),
        ),
    ]
