# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-19 00:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilalumno',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alumnol', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Semestre'),
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.Turno'),
        ),
    ]
