# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_auto_20180831_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilalumno',
            name='imagen_alumno',
            field=models.ImageField(blank=True, upload_to='imagen-alumnos', verbose_name='Foto de Perfil'),
        ),
    ]
