# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-16 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=25, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('folio', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Folio')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.ProductoClinica')),
            ],
        ),
        migrations.AddField(
            model_name='productoclinica',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.TipoProducto'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caja.Venta'),
        ),
    ]
