# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-31 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='ventas',
        ),
        migrations.AlterField(
            model_name='productoclinica',
            name='tipo',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='TipoProducto',
        ),
    ]
