# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0002_auto_20180831_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoclinica',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Precio'),
        ),
    ]
