# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-01 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caja', '0003_productoclinica_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoclinica',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='productoclinica',
            name='tipo',
            field=models.CharField(max_length=150, verbose_name='Tipo'),
        ),
    ]
