from django import forms
from models import HistoriaClinica, HistoriaClinicaControlado, PlanTratamiento, PlanEjecucion, HistoriaClinicaIntegral


class HistoriaClinica_Form(forms.ModelForm):

	class Meta:
		model = HistoriaClinica 

		fields = (
			'folio',
			'nommbre_paciente',
			'edad',
			'Sexo',
			'Estado_Civil',
			'Tel',
			'Ocupacion',
			'Domicilio',
			'curp',
			'Motivo_Consulta',
			'Signos_Sintomas',
			'Ante_Pato',
			'ultimos_meses',
			'tipo_atencion',
			'alergico',
			'tipo_alergia',
			'cardio',
			'diabetes', 
			'hipertencion',
			'otras_enfermedades',
			'medicamentos',
			'medi_cual',
			'medi_motivo',
			't_arterial',
			'pulso',
			'temperatura',
			'f_respiratoria',
			'peso',
			'talla',
			'hallazgo_dientes',
			'hallazgo_tejidos',
			'hallazgo_piel_an',
			'radiografico',
			'interpretacion_radio',
			'diagnostico',
			'pronostico',
			'tratamiento_seguimiento',
			'costo',
			'aut_docente',
			'descrip_act',
			'descrip_notas',
			)
class Historia_Clinica_Controlado(forms.ModelForm):
	class Meta:
		model=HistoriaClinicaControlado

		fields = (
			'folio',
			'nommbre_paciente',
			'edad',
			'Sexo',
			'Estado_Civil',
			'Tel',
			'Ocupacion',
			'Domicilio',
			'curp', 
			'padecimiento', 
			'antecedentes',
			'np_domiciliarios',
			'np_higiene_vivienda',
			'np_higiene_personal',
			'np_higiene_bucal',
			'np_alimentacion',
			'inmunizaciones',
			'pp_nutricionales',
			'pp_cardiacos',
			'pp_hepaticos',
			'pp_trans_sexual',
			'aa_medicamentos',
			'cuales_medicamentos',
			'aa_alimentos',
			'cuales_alimentos',
			'aa_entorno',
			'anestesia',
			'anestesia_especificacion',
			'reaccion_adversa',
			'reaccion_especificacion',
			'ultimos_meses_medicos',
			'motivo_medicos',
			'ultimos_meses_hospi',
			'motivo_hospi',
			'tomando_medicamento',
			'medi_cuales',
			'medi_motivo',
			'trans_sangre',
			'tras_sangre_motivo',
			'trans_sangre_fecha',
			'num_embarazos',
			'num_partos',
			'cesareas',
			'abortos',
			'complicaciones',
			'inter_digestivo',
			'inter_respiratorio',
			'inter_cardio',
			'inter_geni',
			'inter_endo',
			'inter_tegu',
			'inter_mus_esque',
			'inter_nervioso',
			'peso',
			'pulso',
			'frec_cardiaca',
			'frec_resp',
			'temperatura',
			'talla',
			'tipo_craneo',
			'cabeza_perfil',
			'cara',
			'dolor_masticar',
			'dm_tipo',
			'dm_duracion',
			'dificultad_hablar',
			'dh_motivo',
			'ruido_abertura',
			'ruido_cierre',
			'patron_recto',
			'otras_observaciones',
			'labios',
			'ganglios',
			'cervicales',
			'submaxilares',
			'submentonianos',
			'parotideos',
			'preauriculares',
			'auriculares_post',
			'mucosas',
			'mejillas',
			'lengua',
			'piso_boca',
			'region_retromolar',
			'paladar',
			'orofaringe',
			'encias',
			'itsmo_fauces',
			'g_parotidas',
			'g_submaximales',
			'g_sublinguales',
			)

class Plan_TratamientoForm(forms.ModelForm):
	class Meta:
		model = PlanTratamiento

		fields =(
				'actividades',
				'autorizacion',
				)

class Plan_EjecucionForm(forms.ModelForm):
	class Meta:
		model = PlanEjecucion

		fields =(
				'cita',
				'fecha',
				'act',
				'vo_bo',
				)

class Historia_Clinica_IntegralForm(forms.ModelForm):
	class Meta:
		model=HistoriaClinicaIntegral

		fields = (
			'folio',
			'nommbre_paciente',
			'edad',
			'Sexo',
			'Estado_Civil',
			'Tel',
			'Ocupacion',
			'Domicilio',
			'curp', 
			'ipadecimiento', 
			'iantecedentes',
			'inp_domiciliarios',
			'inp_higiene_vivienda',
			'inp_higiene_personal',
			'inp_higiene_bucal',
			'inp_alimentacion',
			'iinmunizaciones',
			'ipp_nutricionales',
			'ipp_cardiacos',
			'ipp_hepaticos',
			'ipp_trans_sexual',
			'iaa_medicamentos',
			'icuales_medicamentos',
			'iaa_alimentos',
			'icuales_alimentos',
			'iaa_entorno',
			'ianestesia',
			'ianestesia_especificacion',
			'ireaccion_adversa',
			'ireaccion_especificacion',
			'iultimos_meses_medicos',
			'imotivo_medicos',
			'iultimos_meses_hospi',
			'imotivo_hospi',
			'itomando_medicamento',
			'imedi_cuales',
			'imedi_motivo',
			'itrans_sangre',
			'itras_sangre_motivo',
			'itrans_sangre_fecha',
			'inum_embarazos',
			'inum_partos',
			'icesareas',
			'iabortos',
			'icomplicaciones',
			'iinter_digestivo',
			'iinter_respiratorio',
			'iinter_cardio',
			'iinter_geni',
			'iinter_endo',
			'iinter_tegu',
			'iinter_mus_esque',
			'iinter_nervioso',
			'ipeso',
			'ipulso',
			'ifrec_cardiaca',
			'ifrec_resp',
			'itemperatura',
			'italla',
			'itipo_craneo',
			'icabeza_perfil',
			'icara',
			'idolor_masticar',
			'idm_tipo',
			'idm_duracion',
			'idificultad_hablar',
			'idh_motivo',
			'iruido_abertura',
			'iruido_cierre',
			'ipatron_recto',
			'iotras_observaciones',
			'ilabios',
			'iganglios',
			'icervicales',
			'isubmaxilares',
			'isubmentonianos',
			'iparotideos',
			'ipreauriculares',
			'iauriculares_post',
			'imucosas',
			'imejillas',
			'ilengua',
			'ipiso_boca',
			'iregion_retromolar',
			'ipaladar',
			'iorofaringe',
			'iencias',
			'iitsmo_fauces',
			'ig_parotidas',
			'ig_submaximales',
			'ig_sublinguales',
			)


