# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConsultaExterna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoexterno',
            name='user_med',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_med', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicoexterno',
            name='valoraciones_iniciales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ConsultaExterna.valoracionInicial'),
        ),
        migrations.AddField(
            model_name='evolucionconsultaexterna',
            name='valoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsultaExterna.valoracionInicial'),
        ),
        migrations.AddField(
            model_name='avancerapido',
            name='valoracionInicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsultaExterna.valoracionInicial'),
        ),
    ]
