# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultaExterna', '0002_auto_20180806_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refcontraref',
            name='urgencia',
            field=models.CharField(max_length=25, verbose_name='Urgencia'),
        ),
    ]
