# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ConsultaExterna', '0002_auto_20180802_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracioninicial',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_externa', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
